version: "3.9"

services:

  timeseries-db:
    image: cassandra:4.1
    container_name: gridsense_cassandra
    restart: unless-stopped

    ports:
      - "9043:9042"

    environment:
      CASSANDRA_CLUSTER_NAME: "GridSenseCluster"
      CASSANDRA_DC: "dc1"
      HEAP_NEWSIZE: "128M"
      MAX_HEAP_SIZE: "512M"

    volumes:
      - cassandra_data:/var/lib/cassandra

    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q '^UN'"]
      interval: 30s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:4.1

    depends_on:
      timeseries-db:
        condition: service_healthy

    volumes:
      - ./cql:/cql

    command: >
      sh -c "
      cqlsh timeseries-db -f /cql/init.cql
      "

  graph-db:
    image: neo4j:5-community
    container_name: gridsense_neo4j
    restart: unless-stopped

    ports:
      - "7475:7474"
      - "7688:7687"

    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_max__size: "512M"

    volumes:
      - neo4j_data:/data
      - ./neo4j/import:/import

    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD} 'RETURN 1' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 8

  catalog-db:
    image: mongo:7

    container_name: gridsense_mongodb
    restart: unless-stopped

    ports:
      - "27018:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - mongo_data:/data/db

  billing-db:
    image: postgres:15

    container_name: gridsense_postgres
    restart: unless-stopped

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - pg_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine

    container_name: gridsense_redis
    restart: unless-stopped

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

  api:
    build: ./api

    container_name: gridsense_api

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      cassandra-init:
        condition: service_completed_successfully

      graph-db:
        condition: service_healthy

      catalog-db:
        condition: service_started

      billing-db:
        condition: service_started

      cache:
        condition: service_started

  seed:
    build: ./api
    restart: "no"

    depends_on:

      cassandra-init:
        condition: service_completed_successfully

      graph-db:
        condition: service_healthy

      catalog-db:
        condition: service_started

      billing-db:
        condition: service_started

      cache:
        condition: service_started

    env_file:
      - .env

    volumes:
      - ./scripts:/api/scripts
      - ./neo4j/import:/neo4j/import

    command: python scripts/seed.py

volumes:
  cassandra_data:
  neo4j_data:
  mongo_data:
  pg_data:
  redis_data:

networks:
  default:
    name: gridsense_net